# Generated by Django 4.2.13 on 2024-09-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
    ]
