# Generated by Django 4.2.13 on 2024-07-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_otp_secret_alter_otp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmation_expiration',
            field=models.DateTimeField(null=True),
        ),
    ]
