# Generated by Django 4.2.13 on 2024-09-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/aizen.jpeg', null=True, upload_to='avatars/'),
        ),
    ]
