# Generated by Django 4.2.13 on 2024-07-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_confirmation_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirmation_expiration',
        ),
    ]
