# Generated by Django 4.2.13 on 2024-08-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
