# Generated by Django 4.2.13 on 2024-07-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_last_password_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_password_change',
        ),
    ]
