# Generated by Django 4.2.13 on 2024-07-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_secret_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
