# Generated by Django 3.2.25 on 2024-08-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20240806_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.userconversations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userconversations',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userconversations',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userconversations',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='userconversations',
            name='user',
        ),
    ]
