# Generated by Django 3.2.25 on 2024-08-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_conversation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
