# Generated by Django 3.2.25 on 2024-08-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_conversation_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='sender',
        ),
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(to='chat.User'),
        ),
    ]
