# Generated by Django 5.0.6 on 2024-07-31 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('ROUND_16', 'Round of 16'), ('QUARTERFINALS', 'Quarterfinals'), ('SEMIFINALS', 'Semifinals'), ('FINAL', 'Final')], max_length=20)),
                ('stage_datetime', models.DateTimeField()),
                ('is_ready_to_play', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('tournament_name', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('number_of_players', models.IntegerField(choices=[(4, '4 Players'), (8, '8 Players'), (16, '16 Players')])),
                ('is_accessible', models.BooleanField(default=False)),
                ('access_password', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='Tourn.stage')),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='Tourn.tournament'),
        ),
    ]
