# Generated by Django 4.2.13 on 2024-07-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='stage',
        ),
        migrations.AlterField(
            model_name='stage',
            name='is_ready_to_play',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_accessible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='stage',
            field=models.ManyToManyField(to='Tourn.stage'),
        ),
    ]
