# Generated by Django 4.2.13 on 2024-07-31 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tourn', '0002_remove_player_stage_alter_stage_is_ready_to_play_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='stage',
        ),
        migrations.AddField(
            model_name='player',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='Tourn.stage'),
        ),
    ]
