# Generated by Django 4.2.13 on 2024-07-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourn', '0003_remove_player_stage_player_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='stage',
        ),
        migrations.AddField(
            model_name='player',
            name='stages',
            field=models.ManyToManyField(related_name='players', to='Tourn.stage'),
        ),
    ]
