# Generated by Django 4.2.13 on 2024-07-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourn', '0004_remove_player_stage_player_stages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='stages',
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='tournaments', to='Tourn.player'),
        ),
    ]
