# Generated by Django 4.2.13 on 2024-07-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourn', '0005_remove_player_stages_tournament_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='can_join',
            field=models.BooleanField(default=True),
        ),
    ]
