services:
  back-end:
    build: .
    container_name: back-end
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    networks:
      - ft_transcendence

  chat:
    build: .
    container_name: chat
    volumes:
      - ./myproject/:/app
    ports:
      - "9000:8000"
    networks:
      - ft_transcendence

  front-end:
    container_name: front-end
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./frontend/:/usr/share/nginx/html
    networks:
      - ft_transcendence
    depends_on:
      - back-end
      - chat

networks:
  ft_transcendence: