services:
  db:
    image: postgres
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=ogorfti
      - POSTGRES_PASSWORD=1337
# to visualize the database you need to add a server with postgre container ip
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 5050:80 # 
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=jodegi7270@hutov.com
      - PGADMIN_DEFAULT_PASSWORD=hutov
networks:
  default:
    driver: bridge
    name: my-network