# Generated by Django 3.2.25 on 2024-08-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20240806_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconversations',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.user'),
            preserve_default=False,
        ),
    ]
