# Generated by Django 3.2.25 on 2024-08-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20240807_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='users',
        ),
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(to='chat.User'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.conversation'),
            preserve_default=False,
        ),
    ]
