# Generated by Django 3.2.25 on 2024-08-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20240811_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='title',
            new_name='conversation_name',
        ),
    ]
