# Generated by Django 3.2.25 on 2024-08-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_conversation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='type',
            new_name='chat_or_group',
        ),
    ]
