# Generated by Django 3.2.25 on 2024-08-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_auto_20240825_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='typee',
            new_name='status',
        ),
    ]
