# Generated by Django 3.2.25 on 2024-08-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_rename_sender_message_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='sender',
        ),
    ]
