# Generated by Django 3.2.25 on 2024-08-27 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0025_auto_20240826_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(max_length=2, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
