# Generated by Django 3.2.25 on 2024-08-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_alter_message_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
