# Generated by Django 3.2.25 on 2024-08-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_remove_message_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='users',
            new_name='participants',
        ),
    ]
