import { CoverComponent } from "./CoverComponent.js";
import { CustomGraph } from "./GraphComponent/CustomGraph.js";
import { ProfileComponent } from "./ProfileComponent.js";
import { CustomProgressBar } from "./StatsComponents/LeagueComponents/CustomProgressBar.js";
import { LeagueInfo } from "./StatsComponents/LeagueComponents/LeagueInfo.js";
import { LeagueItem } from "./StatsComponents/LeagueComponents/LeagueItem.js";
import { RecordComponent } from "./StatsComponents/RecordMatchesComponents/RecordComponent.js";
import { StatsContainer } from "./StatsComponents/StatsContainer.js";
import { DateComponent } from "./TableComponents/BodyComponents/Date/DateComponent.js";
import { CustomTable } from "./TableComponents/CustomTable.js";
import { AchievementComponent } from "./UserInfosComponents/AchievementComponent.js";
import { LinkComponent } from "./UserInfosComponents/LinkComponent.js";
import { ProfileInfoComponent } from "./UserInfosComponents/ProfileInfoComponent.js";
import { UserInfoComponent } from "./UserInfosComponents/UserInfoComponent.js";
import { UserInfoContainerComponent } from "./UserInfosComponents/UserInfoContainer.js";

customElements.define("cover-component", CoverComponent);
customElements.define("profile-info-component", ProfileInfoComponent);
customElements.define("user-info-component", UserInfoComponent);
customElements.define("link-component", LinkComponent);
customElements.define("achievement-component", AchievementComponent);
customElements.define("user-info-container", UserInfoContainerComponent);
customElements.define("league-item", LeagueItem);
customElements.define("custom-progress-bar", CustomProgressBar);
customElements.define("record-component", RecordComponent);
customElements.define("league-info", LeagueInfo);
customElements.define("stats-container", StatsContainer);
customElements.define("custom-graph", CustomGraph);
customElements.define("date-component", DateComponent);
window.customElements.define("custom-table", CustomTable);
window.customElements.define("profile-component", ProfileComponent);