# Generated by Django 4.2.13 on 2024-09-02 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('offense', models.IntegerField(default=0)),
                ('consistency', models.IntegerField(default=0)),
                ('Strategy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('league', models.CharField(default='bronze', max_length=100)),
                ('graph', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='Player.graph')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('joinDate', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('stats', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='Player.stats')),
            ],
        ),
    ]
