# Generated by Django 4.2.15 on 2024-08-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('tournament_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_players', models.IntegerField(choices=[(4, '4 Players'), (8, '8 Players'), (16, '16 Players')])),
                ('is_accessible', models.BooleanField(default=True)),
                ('access_password', models.IntegerField(blank=True, null=True)),
                ('can_join', models.BooleanField(default=True)),
                ('players', models.ManyToManyField(blank=True, related_name='tournaments', to='game.player')),
            ],
        ),
    ]
