# Generated by Django 4.2.15 on 2024-08-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_tournament_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
