# Generated by Django 4.2.15 on 2024-08-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_tournament_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
