# Generated by Django 4.2.15 on 2024-08-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_game_looser_game_player_1_game_player_2_game_winner'),
        ('tournament', '0004_alter_tournament_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
            preserve_default=False,
        ),
    ]
