# Generated by Django 4.2.15 on 2024-08-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_game_looser_game_player_1_game_player_2_game_winner'),
        ('tournament', '0005_tournament_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
