# Generated by Django 4.2.13 on 2024-08-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_tournament_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='access_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
