# Generated by Django 4.2.13 on 2024-08-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
