# Generated by Django 4.2.14 on 2024-08-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/%y/%m/%d/'),
        ),
    ]
