# Generated by Django 4.2.14 on 2024-08-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_player_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, upload_to='%y/%m/%d/'),
        ),
    ]
