# Generated by Django 4.2.14 on 2024-08-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_player_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default='default_password', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
