# Generated by Django 4.2.13 on 2024-08-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='player', max_length=50),
        ),
    ]
