# Generated by Django 4.2.14 on 2024-08-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_password_alter_player_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(default='111', max_length=50),
        ),
    ]
