# Generated by Django 4.2.13 on 2024-08-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
