# Generated by Django 4.2.14 on 2024-08-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_player_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
    ]
