# Generated by Django 4.2.14 on 2024-08-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
