# Generated by Django 4.2.13 on 2024-08-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
