# Generated by Django 4.2.13 on 2024-09-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
