# Generated by Django 4.2.13 on 2024-09-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_accept',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
