# Generated by Django 4.2.13 on 2024-09-07 11:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0004_alter_friend_friends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='Friendship',
        ),
    ]
