# Generated by Django 4.2.13 on 2024-09-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_blockuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockUser',
        ),
    ]
