# Generated by Django 4.2.13 on 2024-09-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0009_alter_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockUser',
        ),
    ]
