# Generated by Django 4.2.13 on 2024-09-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0011_blockuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockuser',
            name='blocked',
        ),
    ]
