# Generated by Django 4.2.13 on 2024-09-11 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0012_remove_blockuser_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockuser',
            name='blocked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
