# Generated by Django 4.2.13 on 2024-09-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0013_blockuser_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='friendship',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
