# Generated by Django 4.2.13 on 2024-09-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0014_friendrequest_update_at_friendship_update_at_and_more'),
    ]

    operations = [
    ]
