# Generated by Django 4.2.13 on 2024-08-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('tournament_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_of_players', models.IntegerField(choices=[(4, '4 Players'), (8, '8 Players'), (16, '16 Players')])),
                ('is_accessible', models.BooleanField(blank=True, null=True)),
                ('access_password', models.IntegerField(blank=True, null=True)),
                ('can_join', models.BooleanField(default=True)),
                ('players', models.ManyToManyField(related_name='tournaments', to='TournamentApp.player')),
            ],
        ),
    ]
