# Generated by Django 4.2.13 on 2024-08-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_accessible',
            field=models.BooleanField(default=True),
        ),
    ]
