# Generated by Django 4.2.13 on 2024-08-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentApp', '0002_rename_name_player_username_player_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
