# Generated by Django 3.2.25 on 2024-08-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentApp', '0003_player_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TournamentApp.player'),
            preserve_default=False,
        ),
    ]
