# Generated by Django 3.2.25 on 2024-08-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentApp', '0004_tournament_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='owner',
        ),
    ]
