global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'back-end'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['back-end:8000']

  - job_name: 'exporters'
    static_configs:
      - targets: ['nginx-exporter:9113']
      - targets: ['postgres-exporter:9187']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'rules.yml'

# curl -X POST http://0.0.0.0:9090/-/reload