global:
  scrape_interval: 60s

scrape_configs:

  - job_name: 'prometheus'
    scheme: https
    tls_config:
      ca_file: /etc/ssl/certs/server.cert
      insecure_skip_verify: true
    static_configs:
      - targets: ['prometheus:9090']
      # - targets: ['back-end:8000']
  
  - job_name: 'back-end'
    scheme: https
    tls_config:
      ca_file: /etc/ssl/certs/server.cert
      insecure_skip_verify: true
    static_configs:
      - targets: ['back-end:8000']

  - job_name: 'exporters'
    static_configs:
      - targets: ['nginx-exporter:9113']
      - targets: ['postgres-exporter:9187']

# curl -X POST http://0.0.0.0:9090/-/reload