global:
  scrape_interval: 15s

scrape_configs:
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  
  # - job_name: 'back-end'
  #   scrape_interval: 60s
  #   scheme: https
  #   static_configs:
  #     - targets: ['back-end:8000']
  #   tls_config:
  #     insecure_skip_verify: true
  
  - job_name: 'telegraf'
    static_configs:
      - targets: ['telegraf:9273']

# curl -X POST http://0.0.0.0:9090/-/reload