# Generated by Django 3.2.25 on 2024-08-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfMessage', models.IntegerField(null=True)),
                ('date', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatList',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receiver', to='chat.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='chat.user'),
        ),
        migrations.AddField(
            model_name='friend',
            name='lastMessage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lastMessage', to='chat.message'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user_id1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User1', to='chat.user'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user_id2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User2', to='chat.user'),
        ),
    ]
