# Generated by Django 3.2.25 on 2024-08-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_conversation_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.user'),
            preserve_default=False,
        ),
    ]
