# Generated by Django 4.2.13 on 2024-08-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_alter_user_profile_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('joinDate', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('stats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Profile.stats')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Profile.user')),
            ],
        ),
        migrations.AlterField(
            model_name='achievements',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='Profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='links',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='Profile.userprofile'),
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
