# Generated by Django 4.2.13 on 2024-08-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_user_userprofile_alter_achievements_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='stats',
        ),
    ]
