# Generated by Django 4.2.13 on 2024-08-30 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0008_player_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='stats',
        ),
        migrations.AddField(
            model_name='player',
            name='fullName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='playerStats',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='Profile.stats'),
        ),
        migrations.AddField(
            model_name='stats',
            name='player',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='Profile.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stats',
            name='league',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='stats',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
