# Generated by Django 4.2.13 on 2024-08-30 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_remove_player_stats_player_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playerStats',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='Profile.stats'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='player',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='Profile.player'),
        ),
    ]
