# Generated by Django 4.2.13 on 2024-08-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_alter_player_playerstats_alter_stats_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='player',
        ),
    ]
