# Generated by Django 4.2.13 on 2024-08-30 10:07

from django.db import migrations, models
import django.db.models.base
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_remove_player_playerstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playerStats',
            field=models.OneToOneField(default=django.db.models.base.Model.get_deferred_fields, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='Profile.stats'),
        ),
        migrations.AddField(
            model_name='stats',
            name='player',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='Profile.player'),
        ),
    ]
