# Generated by Django 4.2.13 on 2024-08-30 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0014_alter_stats_loss_alter_stats_rank_alter_stats_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playerStats',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='Profile.stats'),
        ),
    ]
