# Generated by Django 4.2.13 on 2024-08-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0015_alter_player_playerstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='playerStats',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='player',
        ),
    ]
