# Generated by Django 4.2.13 on 2024-08-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0019_alter_stats_loss_alter_stats_rank_alter_stats_win'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.AlterField(
            model_name='stats',
            name='loss',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='win',
            field=models.IntegerField(null=True),
        ),
    ]
